"""new fields in user model

Revision ID: 41597959664e
Revises: 9627fea30db6
Create Date: 2022-07-03 20:26:05.856275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41597959664e'
down_revision = '9627fea30db6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
